# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  Run:
   
    runs-on: [self-hosted]

    steps:

      - uses: actions/checkout@v3

      - name: Setup Enviroment
        run: |
          python -m venv venv
          venv\Scripts\activate
          pip install -r requirements.txt

      
      - name: Execute Unit tests
        run: |
          venv\Scripts\activate
          behave --junit
          
      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v3.1.0
        if: always() 
        with:
          report_paths: '**/reports/*.xml'



